#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

if ! command -v dig >/dev/null 2>&1; then
    echo "Error: the dig command is not installed. Please install it and try again." >&2
    exit 1
fi

if [ "$#" -lt 1 -o "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [<subdomain>]" >&2
    exit 1
fi

domain_information () {
    local domain="$1"
    local subdomain="$2"
    local record_type="$(dig +short "$subdomain.$domain" | awk 'NR==1{print $2}')"
    local destination="$(dig +short "$subdomain.$domain" | awk 'NR==1{print $1}')"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
else
    domain_information "$1" "$2"
fi
