#!/bin/bash

domain=$1
subdomain=$2

function display_info {
  record=$(dig $subdomain.$domain +short | awk '{print $1}')
  type=$(dig $subdomain.$domain +short | awk '{print $4}')
  echo "The subdomain $subdomain is a $type record and points to $record"
}

if [ -z $subdomain ]; then
  display_info www
  display_info 34.229.161.229
  display_info 52.87.215.132
  display_info 34.224.15.114
else
  display_info $subdomain
fi
