#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Create directory for web files and set permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

# Create index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Add custom HTTP response header to Nginx configuration
sudo sed -i 's/# server_tokens off;/add_header X-Served-By $hostname;\n    server_tokens off;/' /etc/nginx/nginx.conf

# Configure redirect for a single page (/redirect_me)
string_for_replacement="server_name _;\n\trewrite ^/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
